application: cloud-computing-cs553
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url:../../../
  static_dir: static

- url: /dataset
  static_dir: static

- url: /static
  static_dir: static

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
